name: FactionsPerms
main: markehme.FactionsPerms.FactionsPerms
authors: ['MarkehMe']
website: http://markeh.me
version: 1.0.0
depend: [ Factions ]
dev-url: http://dev.bukkit.org/bukkit-plugins/FactionsPerms/
