name: FactionsPerms
main: markehme.FactionsPerms.FactionsPerms
authors: ['MarkehMe']
website: http://markeh.me
version: 1.0.0
dev-url: http://dev.bukkit.org/bukkit-plugins/FactionsPerms/
loadbefore: [ Factions, Vault ]